api_version = "2024-07"

[[extensions]]
name = "t:name"
handle = "cart-checkout-validation"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.validation.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.input.variables]
  namespace = "$app:checkout_validation"
  key = "config"
